In [115]:
import os
import pandas as pd
import numpy as np

In [116]:
# DEG file

DEG_file = "/Users/anb/Documents/CMEB-Lab/GSE28735_filtered_de_results_1fc_01pval.tsv"

DEGs = pd.read_csv(
    DEG_file, comment="#", header=0, sep='\t', low_memory=False
)


symbols_file = "/Users/anb/Documents/CMEB-Lab/GENESYMBOL-ENTREZID-TABLE.tsv"

symbols = pd.read_csv(
    symbols_file, comment="#", header=0, sep='\t', low_memory=False
)


anno_file = "/Users/anb/Documents/CMEB-Lab/GSE28735-annotation.tsv"

anno = pd.read_csv(
    anno_file, comment="#", header=0, sep='\t', low_memory=False
)

In [117]:
DEGs

,ID,Gene.Symbol,logFC,AveExpr,t,P.Value,adj.P.Val,B
0,7908072,LAMC2,-2.901654,6.433389,-11.266594,5.472443e-19,8.894810e-15,32.602469
1,7924029,LAMB3,-2.344230,5.563607,-11.151966,9.446986e-19,8.894810e-15,32.074288
2,8037408,KCNN4,-1.048734,4.283838,-11.041594,1.599510e-18,9.144890e-15,31.564728
3,7901175,TSPAN1,-2.726684,6.361040,-10.999252,1.958011e-18,9.144890e-15,31.369001
4,8049487,MLPH,-1.462933,5.189554,-10.954224,2.428148e-18,9.144890e-15,31.160704
...,...,...,...,...,...,...,...,...
434,8042978,REG3G,1.311361,4.898127,3.307574,1.345617e-03,4.893648e-03,-1.544154
435,8041727,SLC3A1,1.073476,5.675153,3.302282,1.368479e-03,4.964327e-03,-1.559677
436,8136807,PRSS2,1.112385,11.067305,3.183073,1.990790e-03,6.785261e-03,-1.904217
437,8020795,TTR,1.542342,8.189632,3.161687,2.127203e-03,7.162053e-03,-1.964962
438,8053341,REG3A,1.623860,6.571806,3.083489,2.703663e-03,8.718267e-03,-2.184274

In [118]:
DEGs.sort_values(['Gene.Symbol', 'adj.P.Val'], ascending=True, inplace=True)
DEGs.drop_duplicates(subset = ["Gene.Symbol"], inplace=True)

In [119]:
DEGs

,ID,Gene.Symbol,logFC,AveExpr,t,P.Value,adj.P.Val,B
216,7993126,ABAT,1.075960,5.321066,6.294687,1.045777e-08,3.349156e-07,9.654083
317,8017885,ABCA8,1.104388,5.268878,5.199117,1.210341e-06,1.548365e-05,5.080275
14,7985310,ABHD17C,-1.128362,5.684631,-9.595829,1.680329e-15,1.977643e-12,24.822651
233,8058591,ACADL,1.668639,4.805143,6.161877,1.896266e-08,5.426838e-07,9.079397
166,7930498,ACSL5,-1.463485,6.778897,-6.795550,1.067370e-09,5.388645e-08,11.861033
...,...,...,...,...,...,...,...,...
141,7976350,UNC79,1.159701,3.669367,7.043648,3.380940e-10,2.158223e-08,12.974302
246,8106743,VCAN,-1.704051,9.183559,-5.974056,4.364194e-08,1.064535e-06,8.275187
160,8169263,VSIG1,-1.995257,4.224582,-6.829115,9.142438e-10,4.795578e-08,12.010940
146,8051322,XDH,-1.133333,3.980811,-7.009188,3.968963e-10,2.450477e-08,12.818973
86,8105300,NaN,-1.609466,5.441803,-7.747298,1.230090e-11,1.619847e-09,16.186905

In [120]:
DEGs.sort_values(['adj.P.Val'], ascending=True, inplace=True)

In [121]:
DEGs

,ID,Gene.Symbol,logFC,AveExpr,t,P.Value,adj.P.Val,B
1,7924029,LAMB3,-2.344230,5.563607,-11.151966,9.446986e-19,8.894810e-15,32.074288
0,7908072,LAMC2,-2.901654,6.433389,-11.266594,5.472443e-19,8.894810e-15,32.602469
2,8037408,KCNN4,-1.048734,4.283838,-11.041594,1.599510e-18,9.144890e-15,31.564728
3,7901175,TSPAN1,-2.726684,6.361040,-10.999252,1.958011e-18,9.144890e-15,31.369001
4,8049487,MLPH,-1.462933,5.189554,-10.954224,2.428148e-18,9.144890e-15,31.160704
...,...,...,...,...,...,...,...,...
433,8126954,PKHD1,1.213036,5.636322,3.402672,9.910898e-04,3.808819e-03,-1.261853
434,8042978,REG3G,1.311361,4.898127,3.307574,1.345617e-03,4.893648e-03,-1.544154
435,8041727,SLC3A1,1.073476,5.675153,3.302282,1.368479e-03,4.964327e-03,-1.559677
437,8020795,TTR,1.542342,8.189632,3.161687,2.127203e-03,7.162053e-03,-1.964962
438,8053341,REG3A,1.623860,6.571806,3.083489,2.703663e-03,8.718267e-03,-2.184274

In [122]:
DEGs.reset_index(inplace=True,drop=True)

In [123]:
DEGs
list(DEGs['Gene.Symbol'])

['LAMB3',
 'LAMC2',
 'KCNN4',
 'TSPAN1',
 'MLPH',
 'S100P',
 'AHNAK2',
 'STYK1',
 'COL17A1',
 'TMPRSS4',
 'GALNT5',
 'MST1R',
 'CDH3',
 'GJB2',
 'ABHD17C',
 'SLC2A1',
 'SDR16C5',
 'RN7SL815P',
 'SLC6A14',
 'PPAPDC1A',
 'CTSE',
 'LAMA3',
 'TMC7',
 'KRT19',
 'SERPINB5',
 'PLEK2',
 'ASAP2',
 'MBOAT2',
 'FBXO32',
 'ITGB4',
 'COL10A1',
 'HOXB5',
 'ITGA2',
 'TRIM29',
 'MIA',
 'SCEL',
 'MICAL2',
 'SLC16A3',
 'CEMIP',
 'FXYD3',
 'TRIM16',
 'RHBDL2',
 'MTMR11',
 'CEACAM5',
 'FER1L4',
 'ITGA11',
 'COL11A1',
 'NQO1',
 'RUNX2',
 'EGLN3',
 'NOX4',
 'BCAS1',
 'AGR2',
 'POSTN',
 'ESM1',
 'CEACAM6',
 'S100A16',
 'RNU6-1340P',
 'ECT2',
 'TNS4',
 'SEMA7A',
 'ITGA3',
 'FERMT1',
 'APOL1',
 'FGD6',
 'EFNA5',
 'PTPRR',
 'GPRC5A',
 'FN1',
 'CAPG',
 'PCDH7',
 'CXCL12',
 'CDCP1',
 'LONRF2',
 'ERO1L',
 'MET',
 'AOX1',
 'IGFL2',
 'LMO7',
 'LMO3',
 'MMP11',
 'EPHX2',
 'PKM',
 'ANO1',
 'EFNB2',
 'NTM',
 nan,
 'ANGPTL1',
 'SGIP1',
 'IFI27',
 'TTN',
 'PGM2L1',
 'CEACAM1',
 'ADAMTS12',
 'ITGB6',
 'INPP4B',
 'SLC7A2',
 'RTKN2',
 'CLU',
 'TSPAN7',
 'FOXQ1',
 'CCDC141',
 'LEF1',
 'MYOF',
 'ANLN',
 'KRT17P2',
 'ANXA10',
 'ANTXR1',
 'ERO1LB',
 'LIFR',
 'HK2',
 'CTHRC1',
 'SLPI',
 'CST2',
 'MMP14',
 'HIST1H3H',
 'UGT1A1',
 'IL1RAP',
 'ARNTL2',
 'GPR110',
 'LOXL2',
 'LIPH',
 'ANKRD22',
 'CENPF',
 'SYTL2',
 'BTG2',
 'SULF1',
 'KLKB1',
 'SLC9A2',
 'KRT17',
 'PROX1',
 'CST1',
 'NMU',
 'CLDN18',
 'PADI1',
 'PLAU',
 'ADAMTS6',
 'CCL20',
 'UNC79',
 'OSBPL3',
 'OAS1',
 'S100A14',
 'ADHFE1',
 'SLC6A6',
 'XDH',
 'P4HA1',
 'OCIAD2',
 'INHBA',
 'SEMA6A',
 'FLRT2',
 'DPCR1',
 'MALL',
 'TRIM31',
 'PRKAR2B',
 'PLAC8',
 'AK4',
 'BAIAP2L1',
 'KIF1A',
 'VSIG1',
 'LY75-CD302',
 'HIST1H3I',
 'AFAP1-AS1',
 'ESRRG',
 'ACSL5',
 'SLC44A4',
 'TPX2',
 'ST6GALNAC1',
 'ENO2',
 'TOP2A',
 'SLC16A12',
 'PCSK1',
 'MELK',
 'ANXA8',
 'IAPP',
 'MCOLN3',
 'MUC16',
 'GPR98',
 'RAI14',
 'BEX1',
 'CXCL5',
 'ADAM9',
 'IGF2BP3',
 'EPHA4',
 'MKI67',
 'CHST9',
 'DKK1',
 'CD109',
 'ATP2C2',
 'NRP2',
 'CDH11',
 'MMP12',
 'EDNRA',
 'PLA2R1',
 'THBS2',
 'COL8A1',
 'GREM1',
 'HEPH',
 'MMP9',
 'ASPM',
 'OAS2',
 'TMC5',
 'DCBLD2',
 'KIF23',
 'COL12A1',
 'RGN',
 'TFF1',
 'NRCAM',
 'ABAT',
 'TMEM45B',
 'SV2B',
 'KRT7',
 'DDX60',
 'PDK4',
 'ATRNL1',
 'KIAA1324',
 'LTBP1',
 'DLGAP5',
 'DGKH',
 'FAM150B',
 'CORIN',
 'ALDH1A1',
 'MATN3',
 'PLAT',
 'EDIL3',
 'ACADL',
 'IL1R2',
 'NPR3',
 'ADH1B',
 'FUT3',
 'MXRA5',
 'KYNU',
 'IL2RG',
 'C6',
 'CTNND2',
 'F11',
 'VCAN',
 'FER1L6',
 'FNDC1',
 'AEBP1',
 'PAK3',
 'TGFBI',
 'COMP',
 'TMED6',
 'RNU6-570P',
 'ETV1',
 'TGM2',
 'DHRS9',
 'CYP2C18',
 'GABRP',
 'GCNT3',
 'LRRN1',
 'BACE1',
 'CD36',
 'C5',
 'RNA5SP385',
 'ALB',
 'G6PC2',
 'SLC22A3',
 'NR5A2',
 'ANXA3',
 'GRB14',
 'ANPEP',
 'BGN',
 'ADAM28',
 'GPX8',
 'SCNN1A',
 'RNU6-287P',
 'C2CD4B',
 'NT5E',
 'AQP12B',
 'SLC26A9',
 'SCG3',
 'ANGPT2',
 'OR8D4',
 'SCGN',
 'COL5A2',
 'PDIA2',
 'TFPI2',
 'RNU4-56P',
 'PXDN',
 'PAIP2B',
 'ANKRD62P1',
 'FAM129A',
 'TRHDE',
 'SLC43A1',
 'NUCB2',
 'FAP',
 'LAMP5',
 'OR4D5',
 'GSTA2',
 'EPB41L4B',
 'GPX2',
 'F8',
 'COL1A2',
 'ACTA2',
 'RBPJL',
 'COL1A1',
 'MUC17',
 'KRT6A',
 'PDZK1',
 'RN7SL186P',
 'DPYSL3',
 'GUCA1C',
 'IGFBP5',
 'SERPINI2',
 'ABCA8',
 'DPT',
 'AQP8',
 'SLC39A5',
 'MUC13',
 'FAM159B',
 'ERP27',
 'SST',
 'CTRL',
 'SULF2',
 'CP',
 'HOMER2',
 'SRPX2',
 'CELP',
 'PNLIPRP1',
 'DPP10',
 'DSG2',
 'EGF',
 'CTRC',
 'PAH',
 'RNU6-776P',
 'LCN2',
 'KLK1',
 'GSTA1',
 'GRPR',
 'MUC1',
 'FCGR3A',
 'RN7SL386P',
 'MIR27B',
 'MT1G',
 'GPHA2',
 'PNLIPRP2',
 'PM20D1',
 'KCNJ16',
 'COL3A1',
 'COL6A3',
 'BNIP3',
 'SLC1A2',
 'FOSB',
 'C7',
 'MIR217',
 'FABP4',
 'NRG4',
 'GP2',
 'TSPAN8',
 'SLC17A4',
 'CELA2B',
 'PLS1',
 'CEL',
 'IFI44L',
 'CLPS',
 'DCDC2',
 'LYVE1',
 'CELA2A',
 'TNFAIP6',
 'CHRM3',
 'GNMT',
 'OLR1',
 'TCN1',
 'HPGD',
 'CUZD1',
 'SULT1B1',
 'FGL1',
 'CELA3B',
 'CTSK',
 'CPA2',
 'MACC1',
 'PLA2G1B',
 'CELA3A',
 'SYCN',
 'TFF2',
 'CHGA',
 'SLC30A8',
 'SLCO1B3',
 'SEMA3C',
 'SULT1C2',
 'SLC16A10',
 'CTRB2',
 'GC',
 'CHRDL1',
 'GATM',
 'SERPINB3',
 'IL22RA1',
 'ADAM12',
 'SERPINA5',
 'PRSS3',
 'DSG3',
 'CPA1',
 'SLC4A4',
 'EPYC',
 'PNLIP',
 'MFAP5',
 'FBN1',
 'ONECUT1',
 'CCL18',
 'MMP1',
 'PRSS3P2',
 'AMY2A',
 'PRSS1',
 'MMP7',
 'REG1P',
 'CPB1',
 'PRSS2',
 'REG1B',
 'AREG',
 'FAM3B',
 'REG1A',
 'PKHD1',
 'REG3G',
 'SLC3A1',
 'TTR',
 'REG3A']

In [124]:
symbols

                    PROBEID   SYMBOL        GENETYPE  ENTREZID
0                   1000_at    MAPK3  protein-coding    5595.0
1                   1001_at     TIE1  protein-coding    7075.0
2                 1002_f_at  CYP2C19  protein-coding    1557.0
3                 1003_s_at    CXCR5  protein-coding     643.0
4                   1004_at    CXCR5  protein-coding     643.0
...                     ...      ...             ...       ...
13470  AFFX-YEL002c/WBP1_at      NaN             NaN       NaN
13471      AFFX-YEL018w/_at      NaN             NaN       NaN
13472  AFFX-YEL021w/URA3_at      NaN             NaN       NaN
13473  AFFX-YEL024w/RIP1_at      NaN             NaN       NaN
13474       AFFX-hum_alu_at      NaN             NaN       NaN

[13475 rows x 4 columns]

In [125]:
symbols.sort_values(['SYMBOL'], axis=0, ascending=True, inplace=True)

In [126]:
symbols.drop_duplicates(subset = ["SYMBOL"], inplace=True)

In [127]:
symbols.dropna(subset = ["SYMBOL"], inplace=True)

In [128]:
symbols.reset_index(inplace=True,drop=True)

In [129]:
symbols

       PROBEID SYMBOL        GENETYPE  ENTREZID
0     36512_at  AADAC  protein-coding      13.0
1     39456_at   AAK1  protein-coding   22848.0
2     38434_at   AAMP  protein-coding      14.0
3     36332_at  AANAT  protein-coding      15.0
4     36185_at  AARS1  protein-coding      16.0
...        ...    ...             ...       ...
9525  36373_at   ZXDA  protein-coding    7789.0
9526  36373_at   ZXDB  protein-coding  158586.0
9527  36958_at    ZYX  protein-coding    7791.0
9528  38626_at  ZZEF1  protein-coding   23140.0
9529  36456_at   ZZZ3  protein-coding   26009.0

[9530 rows x 4 columns]

In [130]:
symbols[symbols['SYMBOL'] == 'LAMB3']

       PROBEID SYMBOL        GENETYPE  ENTREZID
4426  36929_at  LAMB3  protein-coding    3914.0

In [131]:
DEGs[DEGs['Gene.Symbol'] == 'LAMB3']

,ID,Gene.Symbol,logFC,AveExpr,t,P.Value,adj.P.Val,B
0,7924029,LAMB3,-2.34423,5.563607,-11.151966,9.446986e-19,8.894810e-15,32.074288

In [132]:
symbols['Gene.Symbol'] = symbols['SYMBOL'].copy()

In [133]:
symbols

       PROBEID SYMBOL        GENETYPE  ENTREZID Gene.Symbol
0     36512_at  AADAC  protein-coding      13.0       AADAC
1     39456_at   AAK1  protein-coding   22848.0        AAK1
2     38434_at   AAMP  protein-coding      14.0        AAMP
3     36332_at  AANAT  protein-coding      15.0       AANAT
4     36185_at  AARS1  protein-coding      16.0       AARS1
...        ...    ...             ...       ...         ...
9525  36373_at   ZXDA  protein-coding    7789.0        ZXDA
9526  36373_at   ZXDB  protein-coding  158586.0        ZXDB
9527  36958_at    ZYX  protein-coding    7791.0         ZYX
9528  38626_at  ZZEF1  protein-coding   23140.0       ZZEF1
9529  36456_at   ZZZ3  protein-coding   26009.0        ZZZ3

[9530 rows x 5 columns]

In [134]:
df = symbols[['ENTREZID','Gene.Symbol']].astype(str)

In [135]:
df_G_E = pd.merge(left=DEGs.astype(str), right=df, how = 'left', on = "Gene.Symbol")

In [136]:
df_G_E

,ID,Gene.Symbol,logFC,AveExpr,t,P.Value,adj.P.Val,B,ENTREZID
0,7924029,LAMB3,-2.3442297777777705,5.563606666666667,-11.15196616554734,9.446986123516018e-19,8.894809784596507e-15,32.074287928977064,3914.0
1,7908072,LAMC2,-2.901653555555548,6.433389,-11.26659443907455,5.472443091455584e-19,8.894809784596507e-15,32.60246854812727,3918.0
2,8037408,KCNN4,-1.0487335555555513,4.283838111111111,-11.041593603942951,1.5995098152444301e-18,9.14488960905882e-15,31.564727643965725,3783.0
3,7901175,TSPAN1,-2.726684444444439,6.36104,-10.999252368090824,1.9580108448891633e-18,9.14488960905882e-15,31.36900105709364,10103.0
4,8049487,MLPH,-1.462932666666665,5.189554111111111,-10.954223568986311,2.428147631315071e-18,9.14488960905882e-15,31.160703870439495,NaN
...,...,...,...,...,...,...,...,...,...
412,8126954,PKHD1,1.2130362222222253,5.636322111111111,3.402671614774712,0.000991089785332016,0.0038088187239973,-1.2618526167263946,NaN
413,8042978,REG3G,1.311361111111112,4.898126555555556,3.3075735118505536,0.0013456168122411,0.004893648163637,-1.5441540793456463,NaN
414,8041727,SLC3A1,1.0734760000000063,5.6751526666666665,3.302282407717004,0.0013684786899432,0.0049643271451205,-1.5596774979950334,NaN
415,8020795,TTR,1.5423422222222296,8.189632444444445,3.161687158058157,0.0021272032524776,0.0071620533608808,-1.9649615597233967,7276.0
416,8053341,REG3A,1.6238604444444509,6.571805777777778,3.083488838037367,0.0027036626533578,0.008718266995233,-2.184273933889684,5068.0

In [137]:
anno

,ID,GB_LIST,SPOT_ID,seqname,RANGE_GB,RANGE_STRAND,RANGE_START,RANGE_STOP,total_probes,gene_assignment,mrna_assignment,category,Gene.Symbol
0,7896736,NaN,chr1:53049-54936,chr1,NC_000001.10,+,53049,54936,7,---,NONHSAT060105 // NONCODE // Non-coding transcr...,main,NaN
1,7896742,"NR_024437,XM_006711854,XM_006726377,XR_430662,...",chr1:334129-334296,chr1,NC_000001.10,+,334129,334296,6,NR_024437 // LOC728323 // uncharacterized LOC7...,NR_024437 // RefSeq // Homo sapiens uncharacte...,main,LOC728323
2,7896744,"NM_001005221,NM_001005224,NM_001005277,NM_0010...",chr1:367659-368597,chr1,NC_000001.10,+,367659,368597,36,"NM_001005221 // OR4F29 // olfactory receptor, ...",NM_001005221 // RefSeq // Homo sapiens olfacto...,main,OR4F29
3,7896746,"AK074482,NC_001807",chr1:564951-565019,chr1,NC_000001.10,+,564951,565019,28,ENST00000387377 // MT-TM // mitochondrially en...,ENST00000387377 // ENSEMBL // mt_genbank_impor...,main,MT-TM
4,7896748,NC_001807,chr1:566062-566129,chr1,NC_000001.10,+,566062,566129,24,ENST00000387382 // MT-TW // mitochondrially en...,ENST00000387382 // ENSEMBL // mt_genbank_impor...,main,MT-TW
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18826,8180111,"NM_001270401,NM_021976,AK300402,AK301096,AK302...",chr6:33162420-33168370,chr6,NC_000006.11,-,33162420,33168370,31,"NM_001270401 // RXRB // retinoid X receptor, b...",NM_001270401 // RefSeq // Homo sapiens retinoi...,main,RXRB
18827,8180123,"NM_001289174,NM_001289175,NM_001289176,NM_0225...",chr6:33218055-33239604,chr6,NC_000006.11,-,33218055,33239604,24,NM_001289174 // VPS52 // vacuolar protein sort...,NM_001289174 // RefSeq // Homo sapiens vacuola...,main,VPS52
18828,8180144,"NM_001243738,NM_004761,AB012295,AK294442,BC000...",chr6:33259432-33266752,chr6,NC_000006.11,-,33259432,33266752,27,NM_001243738 // RGL2 // ral guanine nucleotide...,NM_001243738 // RefSeq // Homo sapiens ral gua...,main,RGL2
18829,8180166,"NM_003190,NM_172208,NM_172209,AB010639,AF00951...",chr6:33267471-33282021,chr6,NC_000006.11,-,33267471,33282021,24,NM_003190 // TAPBP // TAP binding protein (tap...,NM_003190 // RefSeq // Homo sapiens TAP bindin...,main,TAPBP
18830,8180179,"NM_001141969,NM_001141970,NM_001350,AB209493,A...",chr6:33286389-33290704,chr6,NC_000006.11,-,33286389,33290704,30,NM_001141969 // DAXX // death-domain associate...,NM_001141969 // RefSeq // Homo sapiens death-d...,main,DAXX

In [138]:
anno

,ID,GB_LIST,SPOT_ID,seqname,RANGE_GB,RANGE_STRAND,RANGE_START,RANGE_STOP,total_probes,gene_assignment,mrna_assignment,category,Gene.Symbol
0,7896736,NaN,chr1:53049-54936,chr1,NC_000001.10,+,53049,54936,7,---,NONHSAT060105 // NONCODE // Non-coding transcr...,main,NaN
1,7896742,"NR_024437,XM_006711854,XM_006726377,XR_430662,...",chr1:334129-334296,chr1,NC_000001.10,+,334129,334296,6,NR_024437 // LOC728323 // uncharacterized LOC7...,NR_024437 // RefSeq // Homo sapiens uncharacte...,main,LOC728323
2,7896744,"NM_001005221,NM_001005224,NM_001005277,NM_0010...",chr1:367659-368597,chr1,NC_000001.10,+,367659,368597,36,"NM_001005221 // OR4F29 // olfactory receptor, ...",NM_001005221 // RefSeq // Homo sapiens olfacto...,main,OR4F29
3,7896746,"AK074482,NC_001807",chr1:564951-565019,chr1,NC_000001.10,+,564951,565019,28,ENST00000387377 // MT-TM // mitochondrially en...,ENST00000387377 // ENSEMBL // mt_genbank_impor...,main,MT-TM
4,7896748,NC_001807,chr1:566062-566129,chr1,NC_000001.10,+,566062,566129,24,ENST00000387382 // MT-TW // mitochondrially en...,ENST00000387382 // ENSEMBL // mt_genbank_impor...,main,MT-TW
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18826,8180111,"NM_001270401,NM_021976,AK300402,AK301096,AK302...",chr6:33162420-33168370,chr6,NC_000006.11,-,33162420,33168370,31,"NM_001270401 // RXRB // retinoid X receptor, b...",NM_001270401 // RefSeq // Homo sapiens retinoi...,main,RXRB
18827,8180123,"NM_001289174,NM_001289175,NM_001289176,NM_0225...",chr6:33218055-33239604,chr6,NC_000006.11,-,33218055,33239604,24,NM_001289174 // VPS52 // vacuolar protein sort...,NM_001289174 // RefSeq // Homo sapiens vacuola...,main,VPS52
18828,8180144,"NM_001243738,NM_004761,AB012295,AK294442,BC000...",chr6:33259432-33266752,chr6,NC_000006.11,-,33259432,33266752,27,NM_001243738 // RGL2 // ral guanine nucleotide...,NM_001243738 // RefSeq // Homo sapiens ral gua...,main,RGL2
18829,8180166,"NM_003190,NM_172208,NM_172209,AB010639,AF00951...",chr6:33267471-33282021,chr6,NC_000006.11,-,33267471,33282021,24,NM_003190 // TAPBP // TAP binding protein (tap...,NM_003190 // RefSeq // Homo sapiens TAP bindin...,main,TAPBP
18830,8180179,"NM_001141969,NM_001141970,NM_001350,AB209493,A...",chr6:33286389-33290704,chr6,NC_000006.11,-,33286389,33290704,30,NM_001141969 // DAXX // death-domain associate...,NM_001141969 // RefSeq // Homo sapiens death-d...,main,DAXX

In [139]:
anno_ge = pd.merge(left=anno.astype(str), right=df, how = 'left', on = "Gene.Symbol")

In [141]:
anno_ge[anno_ge["Gene.Symbol"] == "LAMB3"]

,ID,GB_LIST,SPOT_ID,seqname,RANGE_GB,RANGE_STRAND,RANGE_START,RANGE_STOP,total_probes,gene_assignment,mrna_assignment,category,Gene.Symbol,ENTREZID
1803,7924029,"NM_000228,NM_001017402,NM_001127641,AK296851,A...",chr1:209788215-209825820,chr1,NC_000001.10,-,209788215,209825820,31,"NM_000228 // LAMB3 // laminin, beta 3 // 1q32 ...","NM_000228 // RefSeq // Homo sapiens laminin, b...",main,LAMB3,3914.0

In [143]:
DEGs

,ID,Gene.Symbol,logFC,AveExpr,t,P.Value,adj.P.Val,B
0,7924029,LAMB3,-2.344230,5.563607,-11.151966,9.446986e-19,8.894810e-15,32.074288
1,7908072,LAMC2,-2.901654,6.433389,-11.266594,5.472443e-19,8.894810e-15,32.602469
2,8037408,KCNN4,-1.048734,4.283838,-11.041594,1.599510e-18,9.144890e-15,31.564728
3,7901175,TSPAN1,-2.726684,6.361040,-10.999252,1.958011e-18,9.144890e-15,31.369001
4,8049487,MLPH,-1.462933,5.189554,-10.954224,2.428148e-18,9.144890e-15,31.160704
...,...,...,...,...,...,...,...,...
412,8126954,PKHD1,1.213036,5.636322,3.402672,9.910898e-04,3.808819e-03,-1.261853
413,8042978,REG3G,1.311361,4.898127,3.307574,1.345617e-03,4.893648e-03,-1.544154
414,8041727,SLC3A1,1.073476,5.675153,3.302282,1.368479e-03,4.964327e-03,-1.559677
415,8020795,TTR,1.542342,8.189632,3.161687,2.127203e-03,7.162053e-03,-1.964962
416,8053341,REG3A,1.623860,6.571806,3.083489,2.703663e-03,8.718267e-03,-2.184274

In [144]:
out_dir = "/Users/anb/Documents/CMEB-Lab/"


anno_ge.to_csv(os.path.join(out_dir, "/Users/anb/Documents/CMEB-Lab/GSE28735-annotation-sym-entrez.tsv"), sep='\t', index=False)
df_G_E.to_csv(os.path.join(out_dir, "GSE28735_filtered_de_results_1fc_01pval_dupsdropped-GS-EID.tsv"), sep='\t', index=False)
df_G_E[['Gene.Symbol']].to_csv(os.path.join(out_dir, "GSE28735_filtered_de_results_1fc_01pval_dupsdropped_genes-GS-EID.tsv"), sep='\t', index=False)

Stronger threshold

In [ ]:
# DEG file

DEG_file = "/Users/anb/Documents/CMEB-Lab/ESCC-Drug-Repositioning/DR-escc-data/output/GSE23400/filtered_de_results_1-5fc_01pval.tsv"

DEGs15fcp01 = pd.read_csv(
    DEG_file, comment="#", header=0, sep='\t', low_memory=False
)

In [ ]:
DEGs15fcp01

In [ ]:
DEGs15fcp01['Gene.Symbol-drop-slash'] = DEGs15fcp01['Gene.Symbol'].str.split(' ').str[0]

In [ ]:
DEGs15fcp01

In [ ]:
DEGs15fcp01['Gene.Symbol-drop-slashdash'] = DEGs15fcp01['Gene.Symbol-drop-slash'].str.split('-').str[0]

In [ ]:
DEGs15fcp01

In [ ]:
DEGs15fcp01['Gene.Symbol'] = DEGs15fcp01['Gene.Symbol-drop-slashdash'].copy()

In [ ]:
DEGs15fcp01

In [ ]:
DEGs15fcp01_mini = DEGs15fcp01[['Gene.Symbol', 'logFC', 'P.Value']]

In [ ]:
DEGs15fcp01_mini.sort_values(['Gene.Symbol', 'P.Value'], ascending=True, inplace=True)
DEGs15fcp01_mini.drop_duplicates(subset = ["Gene.Symbol"], inplace=True)



DEGs15fcp01.sort_values(['Gene.Symbol', 'P.Value'], ascending=True, inplace=True)
DEGs15fcp01.drop_duplicates(subset = ["Gene.Symbol"], inplace=True)

In [ ]:
DEGs15fcp01_mini

In [ ]:
DEGs15fcp01_mini.sort_values(['P.Value'], ascending=True, inplace=True)

DEGs15fcp01.sort_values(['P.Value'], ascending=True, inplace=True)

In [ ]:
DEGs15fcp01_mini

In [ ]:
DEGs15fcp01

In [ ]:
DEGs15fcp01_mini.reset_index(inplace=True,drop=True)

In [ ]:
DEGs15fcp01.reset_index(inplace=True,drop=True)

In [ ]:
out_dir = "/Users/anb/Documents/CMEB-Lab/ESCC-Drug-Repositioning/DR-escc-data/output/GSE23400/DEG-analysis/1-5fc_pval01"

DEGs15fcp01_mini.to_csv(os.path.join(out_dir, "DEGs15fcp01_mini_sorted_pval.tsv"), sep='\t', index=False)
DEGs15fcp01_mini[['Gene.Symbol']].to_csv(os.path.join(out_dir, "DEGs15fcp01_mini_sorted_pval_genes.tsv"), sep='\t', index=False)

DEGs15fcp01.to_csv(os.path.join(out_dir, "filtered_de_results_1fc_05pval_dupsdropped.tsv"), sep='\t', index=False)
DEGs15fcp01[['Gene.Symbol']].to_csv(os.path.join(out_dir, "filtered_de_results_1-5fc_01pval_dupsdropped_genes.tsv"), sep='\t', index=False)